### ISSUE TITLE
Status column

### ISSUE THREAD

**Issue by Djeisen642** [anjosh/htm-project-backend#5]
Add status column to model/person.js  
Probably want to make an ENUM, like preferred contact method

**Comment by Djeisen642** [comment]
Or Status table for multiple statuses. @anjosh thoughts?

**Comment by anjosh** [comment]
I'm not sure. good question. I think we should look at this to begin with for statuses. I think there'll be multiple with a timestamp assigned to each.

**Comment by anjosh** [comment]
https://drive.google.com/file/d/0B_uVEsYLmMO6VEJJa08xb2M0Zl9pMmNnb0lRRE55aWozdHRZ/view?usp=sharing

**Comment by anjosh** [comment]
Specifically the blessing steps. I think that's what we need first as statues:
Blessing Steps Completed (Enter Date)					
Donation	Holy Wine	Benediction	Chastening Ceremony	40-Day Seperation	3-Day Ceremony

**Comment by anjosh** [comment]
Created a ActionType table in https://github.com/anjosh/htm-project-backend/pull/9
