### ISSUE TITLE
Status column migration

### ISSUE THREAD

**Issue by Djeisen642** [anjosh/htm-project-backend#6]
When making a new column, there needs to be a migration. Remove the current migrations because they are not needed and add one for status.

**Comment by anjosh** [comment]
Created an Action and ActionType table but did not create a migration. Not so familiar with them and their importance so will need to be educated on that.

**Comment by Djeisen642** [comment]
If we were working with production data, then you would need to migrate from one table schema to another. You can't just move data from an old DB to a new DB.

**Comment by anjosh** [comment]
So for instance where adding a column to a table?

I didn't seem to need it when I created the new Action and ActionType tables.

**Comment by Djeisen642** [comment]
I don't remember how the DB is set up. But if the DB has data in it, then it won't be able to use the new columns unless certain SQL commands are run that create the new columns.

**Comment by anjosh** [comment]
Thanks Jason that's helpful. I'm gonna close this for now since I don't see any action needed at the moment
