### ISSUE TITLE
Update person API for ActionTypes

### ISSUE THREAD

**Issue by Djeisen642** [anjosh/htm-project-backend#7]
update /create and post /:person_id

**Comment by anjosh** [comment]
How do we want to update it? To also work with status?

**Comment by Djeisen642** [comment]
That's right. I don't know what the statuses should be. Either this should be an enum. Or it should be another table associated with people, because people can have multiple statuses

**Comment by anjosh** [comment]
Using the term `Action` now to handle Blessing Steps. Have added them to DB but not created API yet.

**Comment by anjosh** [comment]
Some of this work has been complete in #9 but we still need to update POST /:person_id

**Comment by anjosh** [comment]
The direction I'd like to go in for this is not to make the person API update Actions but have an Actions API. This will require a different design for Actions which we are working on. Closing this issue.
